import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { PurchaseOrdersService } from './purchase-orders.service';
import { TenancyContext } from '../common/tenancy.context';

@Injectable()
export class AutoReorderService {
  private readonly logger = new Logger(AutoReorderService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly poService: PurchaseOrdersService,
  ) {}

  // Run at midnight every day
  @Cron(CronExpression.EVERY_DAY_AT_MIDNIGHT)
  async handleAutoReorder() {
    this.logger.log('Starting Auto-Reorder Scan...');

    // Find all parts that need reordering
    // Prisma does not support referencing another column directly in the where clause easily (e.g. quantity: { lte: minQuantity })
    // So we fetch all enabled parts and filter in memory, or use $queryRaw. Since it's a cron, in-memory is fine for moderate sizes.
    const eligibleParts = await this.prisma.part.findMany({
      where: {
        autoReorderEnabled: true,
        vendorId: { not: null },
        deletedAt: null,
      },
      include: {
        vendor: true,
      },
    });

    const partsToReorder = eligibleParts.filter(p => p.quantity <= p.minQuantity);

    this.logger.log(`Found ${partsToReorder.length} parts eligible for auto-reorder.`);

    // Group parts by organization and vendor to consolidate POs
    const groupedOrders = new Map<string, typeof partsToReorder>();

    for (const part of partsToReorder) {
      // Check if there is already an active (unreceived) PO for this part
      const existingPoItems = await this.prisma.purchaseOrderItem.findMany({
        where: {
          partId: part.id,
          purchaseOrder: {
            status: { notIn: ['RECEIVED', 'DENIED', 'COMPLETED'] },
            deletedAt: null,
          }
        }
      });

      if (existingPoItems.length > 0) {
        this.logger.debug(`Skipping part ${part.name} - already has an active PO pending.`);
        continue;
      }

      // Group by Org + Vendor
      const key = `${part.organizationId}_${part.vendorId}`;
      if (!groupedOrders.has(key)) {
        groupedOrders.set(key, []);
      }
      groupedOrders.get(key)!.push(part);
    }

    // Generate the Purchase Orders
    for (const [key, parts] of groupedOrders.entries()) {
      if (parts.length === 0) continue;
      
      const organizationId = parts[0].organizationId;
      const vendorId = parts[0].vendorId;
      
      // Temporarily set Tenancy Context for the POService
      TenancyContext.setContext({
        organizationId: organizationId,
        userId: 'SYSTEM',
        userOrgId: 'SYSTEM',
        role: 'ADMIN',
        roles: [],
      });

      try {
        const items = parts.map(part => {
          // Calculate how many to order to reach max quantity, default to 1 if no max
          const orderQty = part.maxQuantity && part.maxQuantity > part.quantity 
            ? part.maxQuantity - part.quantity 
            : Math.max(1, part.minQuantity - part.quantity + 1);

          return {
            partId: part.id,
            description: `Auto-restock for ${part.name} (${part.partNumber || 'N/A'})`,
            quantity: orderQty,
            unitCost: part.cost ? Number(part.cost) : 0,
          };
        });

        await this.poService.create({
          title: `Automatic Restock - ${new Date().toLocaleDateString()}`,
          notes: 'This Purchase Order was automatically generated by the system based on low inventory thresholds.',
          vendorId: vendorId!,
          items: items,
        });

        this.logger.log(`Created auto-reorder PO for vendor ${vendorId} in org ${organizationId}`);
      } catch (error: any) {
        this.logger.error(`Failed to create auto-reorder PO for key ${key}: ${error.message}`);
      }
    }

    this.logger.log('Auto-Reorder Scan Complete.');
  }
}
